# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from allostatic_control/Drive.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Drive(genpy.Message):
  _md5sum = "e4b100e18918e1da885417627a4aa817"
  _type = "allostatic_control/Drive"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 hunger_drive
float32 thirst_drive
float32 temp_drive
float32 adsign
float32 hsign
"""
  __slots__ = ['hunger_drive','thirst_drive','temp_drive','adsign','hsign']
  _slot_types = ['float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       hunger_drive,thirst_drive,temp_drive,adsign,hsign

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Drive, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.hunger_drive is None:
        self.hunger_drive = 0.
      if self.thirst_drive is None:
        self.thirst_drive = 0.
      if self.temp_drive is None:
        self.temp_drive = 0.
      if self.adsign is None:
        self.adsign = 0.
      if self.hsign is None:
        self.hsign = 0.
    else:
      self.hunger_drive = 0.
      self.thirst_drive = 0.
      self.temp_drive = 0.
      self.adsign = 0.
      self.hsign = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_5f().pack(_x.hunger_drive, _x.thirst_drive, _x.temp_drive, _x.adsign, _x.hsign))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.hunger_drive, _x.thirst_drive, _x.temp_drive, _x.adsign, _x.hsign,) = _get_struct_5f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_5f().pack(_x.hunger_drive, _x.thirst_drive, _x.temp_drive, _x.adsign, _x.hsign))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.hunger_drive, _x.thirst_drive, _x.temp_drive, _x.adsign, _x.hsign,) = _get_struct_5f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5f = None
def _get_struct_5f():
    global _struct_5f
    if _struct_5f is None:
        _struct_5f = struct.Struct("<5f")
    return _struct_5f
