// Generated by gencpp from file allostatic_control/Action.msg
// DO NOT EDIT!


#ifndef ALLOSTATIC_CONTROL_MESSAGE_ACTION_H
#define ALLOSTATIC_CONTROL_MESSAGE_ACTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace allostatic_control
{
template <class ContainerAllocator>
struct Action_
{
  typedef Action_<ContainerAllocator> Type;

  Action_()
    : x(0.0)
    , th(0.0)  {
    }
  Action_(const ContainerAllocator& _alloc)
    : x(0.0)
    , th(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _th_type;
  _th_type th;





  typedef boost::shared_ptr< ::allostatic_control::Action_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::allostatic_control::Action_<ContainerAllocator> const> ConstPtr;

}; // struct Action_

typedef ::allostatic_control::Action_<std::allocator<void> > Action;

typedef boost::shared_ptr< ::allostatic_control::Action > ActionPtr;
typedef boost::shared_ptr< ::allostatic_control::Action const> ActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::allostatic_control::Action_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::allostatic_control::Action_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::allostatic_control::Action_<ContainerAllocator1> & lhs, const ::allostatic_control::Action_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.th == rhs.th;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::allostatic_control::Action_<ContainerAllocator1> & lhs, const ::allostatic_control::Action_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace allostatic_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::allostatic_control::Action_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::allostatic_control::Action_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::allostatic_control::Action_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::allostatic_control::Action_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::allostatic_control::Action_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::allostatic_control::Action_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::allostatic_control::Action_<ContainerAllocator> >
{
  static const char* value()
  {
    return "05821a98e59391a8fea77064466b46c2";
  }

  static const char* value(const ::allostatic_control::Action_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x05821a98e59391a8ULL;
  static const uint64_t static_value2 = 0xfea77064466b46c2ULL;
};

template<class ContainerAllocator>
struct DataType< ::allostatic_control::Action_<ContainerAllocator> >
{
  static const char* value()
  {
    return "allostatic_control/Action";
  }

  static const char* value(const ::allostatic_control::Action_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::allostatic_control::Action_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n"
"float32 th\n"
;
  }

  static const char* value(const ::allostatic_control::Action_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::allostatic_control::Action_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.th);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Action_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::allostatic_control::Action_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::allostatic_control::Action_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "th: ";
    Printer<float>::stream(s, indent + "  ", v.th);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALLOSTATIC_CONTROL_MESSAGE_ACTION_H
