// Generated by gencpp from file allostatic_control/GradientInfo.msg
// DO NOT EDIT!


#ifndef ALLOSTATIC_CONTROL_MESSAGE_GRADIENTINFO_H
#define ALLOSTATIC_CONTROL_MESSAGE_GRADIENTINFO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace allostatic_control
{
template <class ContainerAllocator>
struct GradientInfo_
{
  typedef GradientInfo_<ContainerAllocator> Type;

  GradientInfo_()
    : adsign(0.0)
    , hsign(0.0)  {
    }
  GradientInfo_(const ContainerAllocator& _alloc)
    : adsign(0.0)
    , hsign(0.0)  {
  (void)_alloc;
    }



   typedef float _adsign_type;
  _adsign_type adsign;

   typedef float _hsign_type;
  _hsign_type hsign;





  typedef boost::shared_ptr< ::allostatic_control::GradientInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::allostatic_control::GradientInfo_<ContainerAllocator> const> ConstPtr;

}; // struct GradientInfo_

typedef ::allostatic_control::GradientInfo_<std::allocator<void> > GradientInfo;

typedef boost::shared_ptr< ::allostatic_control::GradientInfo > GradientInfoPtr;
typedef boost::shared_ptr< ::allostatic_control::GradientInfo const> GradientInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::allostatic_control::GradientInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::allostatic_control::GradientInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::allostatic_control::GradientInfo_<ContainerAllocator1> & lhs, const ::allostatic_control::GradientInfo_<ContainerAllocator2> & rhs)
{
  return lhs.adsign == rhs.adsign &&
    lhs.hsign == rhs.hsign;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::allostatic_control::GradientInfo_<ContainerAllocator1> & lhs, const ::allostatic_control::GradientInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace allostatic_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::allostatic_control::GradientInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::allostatic_control::GradientInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::allostatic_control::GradientInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::allostatic_control::GradientInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::allostatic_control::GradientInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::allostatic_control::GradientInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::allostatic_control::GradientInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "999d9275d196ff95aab41905a8d95a6c";
  }

  static const char* value(const ::allostatic_control::GradientInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x999d9275d196ff95ULL;
  static const uint64_t static_value2 = 0xaab41905a8d95a6cULL;
};

template<class ContainerAllocator>
struct DataType< ::allostatic_control::GradientInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "allostatic_control/GradientInfo";
  }

  static const char* value(const ::allostatic_control::GradientInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::allostatic_control::GradientInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 adsign\n"
"float32 hsign\n"
;
  }

  static const char* value(const ::allostatic_control::GradientInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::allostatic_control::GradientInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.adsign);
      stream.next(m.hsign);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GradientInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::allostatic_control::GradientInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::allostatic_control::GradientInfo_<ContainerAllocator>& v)
  {
    s << indent << "adsign: ";
    Printer<float>::stream(s, indent + "  ", v.adsign);
    s << indent << "hsign: ";
    Printer<float>::stream(s, indent + "  ", v.hsign);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALLOSTATIC_CONTROL_MESSAGE_GRADIENTINFO_H
