// Generated by gencpp from file allostatic_control/HomeostaticState.msg
// DO NOT EDIT!


#ifndef ALLOSTATIC_CONTROL_MESSAGE_HOMEOSTATICSTATE_H
#define ALLOSTATIC_CONTROL_MESSAGE_HOMEOSTATICSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace allostatic_control
{
template <class ContainerAllocator>
struct HomeostaticState_
{
  typedef HomeostaticState_<ContainerAllocator> Type;

  HomeostaticState_()
    : energy_aV(0.0)
    , water_aV(0.0)
    , temp_aV(0.0)
    , hunger_urgency(0.0)
    , thirst_urgency(0.0)
    , temp_urgency(0.0)
    , adsign(0.0)
    , hsign(0.0)  {
    }
  HomeostaticState_(const ContainerAllocator& _alloc)
    : energy_aV(0.0)
    , water_aV(0.0)
    , temp_aV(0.0)
    , hunger_urgency(0.0)
    , thirst_urgency(0.0)
    , temp_urgency(0.0)
    , adsign(0.0)
    , hsign(0.0)  {
  (void)_alloc;
    }



   typedef float _energy_aV_type;
  _energy_aV_type energy_aV;

   typedef float _water_aV_type;
  _water_aV_type water_aV;

   typedef float _temp_aV_type;
  _temp_aV_type temp_aV;

   typedef float _hunger_urgency_type;
  _hunger_urgency_type hunger_urgency;

   typedef float _thirst_urgency_type;
  _thirst_urgency_type thirst_urgency;

   typedef float _temp_urgency_type;
  _temp_urgency_type temp_urgency;

   typedef float _adsign_type;
  _adsign_type adsign;

   typedef float _hsign_type;
  _hsign_type hsign;





  typedef boost::shared_ptr< ::allostatic_control::HomeostaticState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::allostatic_control::HomeostaticState_<ContainerAllocator> const> ConstPtr;

}; // struct HomeostaticState_

typedef ::allostatic_control::HomeostaticState_<std::allocator<void> > HomeostaticState;

typedef boost::shared_ptr< ::allostatic_control::HomeostaticState > HomeostaticStatePtr;
typedef boost::shared_ptr< ::allostatic_control::HomeostaticState const> HomeostaticStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::allostatic_control::HomeostaticState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::allostatic_control::HomeostaticState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::allostatic_control::HomeostaticState_<ContainerAllocator1> & lhs, const ::allostatic_control::HomeostaticState_<ContainerAllocator2> & rhs)
{
  return lhs.energy_aV == rhs.energy_aV &&
    lhs.water_aV == rhs.water_aV &&
    lhs.temp_aV == rhs.temp_aV &&
    lhs.hunger_urgency == rhs.hunger_urgency &&
    lhs.thirst_urgency == rhs.thirst_urgency &&
    lhs.temp_urgency == rhs.temp_urgency &&
    lhs.adsign == rhs.adsign &&
    lhs.hsign == rhs.hsign;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::allostatic_control::HomeostaticState_<ContainerAllocator1> & lhs, const ::allostatic_control::HomeostaticState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace allostatic_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::allostatic_control::HomeostaticState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::allostatic_control::HomeostaticState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::allostatic_control::HomeostaticState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::allostatic_control::HomeostaticState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::allostatic_control::HomeostaticState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::allostatic_control::HomeostaticState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::allostatic_control::HomeostaticState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a099a68a501f1e47aa53247b3024fb7";
  }

  static const char* value(const ::allostatic_control::HomeostaticState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a099a68a501f1e4ULL;
  static const uint64_t static_value2 = 0x7aa53247b3024fb7ULL;
};

template<class ContainerAllocator>
struct DataType< ::allostatic_control::HomeostaticState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "allostatic_control/HomeostaticState";
  }

  static const char* value(const ::allostatic_control::HomeostaticState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::allostatic_control::HomeostaticState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 energy_aV\n"
"float32 water_aV\n"
"float32 temp_aV\n"
"float32 hunger_urgency\n"
"float32 thirst_urgency\n"
"float32 temp_urgency\n"
"float32 adsign\n"
"float32 hsign\n"
;
  }

  static const char* value(const ::allostatic_control::HomeostaticState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::allostatic_control::HomeostaticState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.energy_aV);
      stream.next(m.water_aV);
      stream.next(m.temp_aV);
      stream.next(m.hunger_urgency);
      stream.next(m.thirst_urgency);
      stream.next(m.temp_urgency);
      stream.next(m.adsign);
      stream.next(m.hsign);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HomeostaticState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::allostatic_control::HomeostaticState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::allostatic_control::HomeostaticState_<ContainerAllocator>& v)
  {
    s << indent << "energy_aV: ";
    Printer<float>::stream(s, indent + "  ", v.energy_aV);
    s << indent << "water_aV: ";
    Printer<float>::stream(s, indent + "  ", v.water_aV);
    s << indent << "temp_aV: ";
    Printer<float>::stream(s, indent + "  ", v.temp_aV);
    s << indent << "hunger_urgency: ";
    Printer<float>::stream(s, indent + "  ", v.hunger_urgency);
    s << indent << "thirst_urgency: ";
    Printer<float>::stream(s, indent + "  ", v.thirst_urgency);
    s << indent << "temp_urgency: ";
    Printer<float>::stream(s, indent + "  ", v.temp_urgency);
    s << indent << "adsign: ";
    Printer<float>::stream(s, indent + "  ", v.adsign);
    s << indent << "hsign: ";
    Printer<float>::stream(s, indent + "  ", v.hsign);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ALLOSTATIC_CONTROL_MESSAGE_HOMEOSTATICSTATE_H
